### PR TITLE
Week picker and fix for issue #116

### PR DESCRIPTION
**Pull request by AbcAeffchen**
Added an option for to use a week picker instead of day picker.
Also added an fix for issue #116 from.

### CODE REVIEW

**Comment by SergioCrisostomo** [comment]
Thank you for this pull request! Nice work you put into this. Could you please use the MooTools code style like https://github.com/mootools/mootools-core/wiki/Syntax-and-Coding-Style-Conventions

Basically not breaking line before a  `if(condition)` and the floowing `{`; check indent in L#35 of `Source/Picker.Date.js`, and also remove space between `function` and the following `(`.

I didn't manage to look at all the code and funcionality. But just wanted to give some feedback this far.

**Comment by arian** [comment]
Indeed, please use the code style that is used elsewhere throughout the code, in this case tabs and what @SergioCrisostomo mentions.

Also, separate pull requests for different fixes would be much appreciated, so a separate pull request for the fix for #116. With git, you could create a new branch, git-rebase or git-cherry pick the right commits.

**Comment by AbcAeffchen** [comment]
You are totally right. I'll fix this. Do I have to close this pull request or can I modify it after fixing this?

**Comment by arian** [comment]
As you used your master branch, it's better to create a new, clean, branch, get the right commits, fix the coding style, and open a new pull request.

**Comment by SergioCrisostomo** [comment]
You are sending this pull request from your master branch, you could make one branch for each change and send the pull request from there. 

You can then close this one by including `closes #161` in the description of the PR that should close this one; and can include `fixes #116` in the PR that fixes the issue 116. That way Github will close it for you when they get merged.

**Comment by SergioCrisostomo** [comment]
(sorry for double posting, @arian was faster answering and I missed that :smile: )

**Comment by AbcAeffchen** [comment]
Thanks. (No problem @SergioCrisostomo :smile:)

As this is the first time I contribute code to an existing project, I made several mistakes. But I hope I fixed them all, and after improving the weekpicker a little more there is a new pull request.

The fix for #116 conflicts with the weekpicker and so I will send an pull request after the PR #162 is accepted.

**Pull request closed without merging**
